export type EraKey =
    | "all"
    | "golden_age"
    | "wars_partitions"
    | "independence"
    | "rebirth"
    | "ww2"
    | "communist"
    | "modern";

export type EraTab = {
    key: EraKey;
    label: string;
};

export type EraKeyNoAll = Exclude<EraKey, "all">;

export type ContentCardItem = {
    id: string;
    eraKeys: EraKeyNoAll[];
    yearLabel: string; //  "1400s" / "1791"
    titleTop: string;  //  "Did You Know?"
    titleBottom: string; // "Poland protected religious freedom early"
    imageUri: string | number;
};

// Detail page data for each POI, keyed by the same id as ContentCardItem.id
export type PoiDetail = {
    id: string;
    eraKeys: EraKeyNoAll[];
    yearLabel: string;
    titleTop: string;
    // Full paragraph used on the main detail under the large image on the left
    description: string;
    // Short summary used when this POI appears as "Related Content"
    summary?: string;
    // Local image for the large hero on the left. Optional: some POIs may not have a dedicated asset yet.
    mainImage?: any;
    // IDs of other cards to show in "Related Content"
    relatedIds: string[];
};

export const POI_DETAILS: Record<string, PoiDetail> = {
    c1: {
        id: "c1",
        eraKeys: ["golden_age"],
        yearLabel: "1400s–1791",
        titleTop: "Did You Know?",
        description:
            "Poland was a Catholic nation but provided legal protection to religious minorities. Protestants, Jews, Muslims, and Orthodox Christians had the freedom to practice their faiths.",
        summary: "Poland protected religious freedom early",
        mainImage: require("../assets/content_images/GoldenAge/GoldenAge_1.png"),
        relatedIds: ["c2", "c3"],
    },
    c2: {
        id: "c2",
        eraKeys: ["golden_age"],
        yearLabel: "1400s–1791",
        titleTop: "Did You Know?",
        description: "From the 1400s to 1791, when people in most countries had few rights, Poland was a Republic in which members of the gentry (szlachta)—about 15% of the population—could vote. Power was vested in an elected parliament (sejm) and kings were elected.",
        summary: "When voting rights were rare, Poland had them",
        mainImage: require("../assets/content_images/GoldenAge/GoldenAge_2.png"),
        relatedIds: ["c1", "c3"],
    },
    c3: {
        id: "c3",
        eraKeys: ["wars_partitions"],
        yearLabel: "1791",
        titleTop: "Did You Know?",
        description: "The first two constitutions in the world were the Constitution of the United States in 1789 and Poland's Constitution of May 3rd 1791.",
        summary: "Poland wrote the world’s second constitution",
        mainImage: require("../assets/content_images/WarsAndPartitions/WarsAndPartitions_1.png"),
        relatedIds: ["c1", "c2"],
    },
    c4: {
        id: "c4",
        eraKeys: ["wars_partitions"],
        yearLabel: "1792",
        titleTop: "Did You Know?",
        description: "During the 1700s corruption weakened a once-vibrant Poland. Wealthy nobles lined their pockets with foreign money which influenced elections and legislation. The Constitution of 1791, designed to limit foreign influence and end corruption was blocked by the enemies of freedom.",
        summary: "How corruption undermined Poland’s freedom",
        mainImage: require("../assets/content_images/WarsAndPartitions/WarsAndPartitions_2.png"),
        relatedIds: ["c5", "c6"],
    },
    c5: {
        id: "c5",
        eraKeys: ["wars_partitions"],
        yearLabel: "1795",
        titleTop: "Did You Know?",
        description: "Prussia, Austria, and Russia bought influence in Poland and then partitioned the country between them. In 1795 Poland disappeared from the map of Europe for 123 years.",
        summary: "How Poland vanished for 123 years",
        mainImage: require("../assets/content_images/WarsAndPartitions/WarsAndPartitions_3.png"),
        relatedIds: ["c4", "c6"],
    },
    c6: {
        id: "c6",
        eraKeys: ["wars_partitions"],
        yearLabel: "1795-1918",
        titleTop: "Did You Know?",
        description: "Although they could not have freedom at home, Polish patriots traveled across the world to help other nations win their freedom. During the American Revolution Thaddeus Kościuszko and Casimir Pułaski helped our country win independence.",
        summary: "Polish heroes helped win American freedom",
        mainImage: require("../assets/content_images/WarsAndPartitions/WarsAndPartitions_4.png"),
        relatedIds: ["c5", "c4"],
    },
    c7: {
        id: "c7",
        eraKeys: ["independence"],
        yearLabel: "1850",
        titleTop: "Did You Know?",
        description: "There are over 800,000 Michiganders with Polish roots. The first Poles arrived in the 1850s and live in all parts of the state, building homes, churches, cities, businesses, and industries.",
        summary: "Polish Roots in Michigan",
        mainImage: require("../assets/content_images/Independence/Independence_1.png"),
        relatedIds: ["c12","c18"],
    },
    c8: {
        id: "c8",
        eraKeys: ["rebirth"],
        yearLabel: "1918",
        titleTop: "Did You Know?",
        description: "After WWI, Russia, Austria, and Germany collapsed and Poland regained her freedom in 1918.",
        summary: "How WWI led to Polish independence",
        mainImage: require("../assets/content_images/Rebirth/Rebirth_1.png"),
        relatedIds: ["c11","c9", "c10"],
    },
    c9: {
        id: "c9",
        eraKeys: ["rebirth"],
        yearLabel: "1920",
        titleTop: "Did You Know?",
        description: "Poles from America joined the Polish Army and provided millions of dollars in humanitarian aid for the new nation.",
        summary: "Polish Americans sent aid and soldiers",
        mainImage: require("../assets/content_images/Rebirth/Rebirth_2.png"),
        relatedIds: ["c8", "c11","c10"],
    },
    c10: {
        id: "c10",
        eraKeys: ["rebirth"],
        yearLabel: "1920",
        titleTop: "Did You Know?",
        description: "After the Russian Revolution, the Communist Red Army sought to crush Poland once again and spread dictatorship and oppression across Europe.",
        summary: "Poland faced the Red Army again",
        mainImage: require("../assets/content_images/Rebirth/Rebirth_3.png"),
        relatedIds: ["c8","c11", "c9"],
    },
    c11: {
        id: "c11",
        eraKeys: ["rebirth"],
        yearLabel: "1920",
        titleTop: "Did You Know?",
        description: "Though outnumbered and alone, the Poles defeated the Communist invasion and saved Europe at the Battle of Warsaw in 1920, known as the “Miracle on the Vistula.”",
        summary: "How Poland turned the tide alone",
        mainImage: require("../assets/content_images/Rebirth/Rebirth_4.png"),
        relatedIds: ["c8", "c10","c9"],
    },
    c12: {
        id: "c12",
        eraKeys: ["rebirth"],
        yearLabel: "1920",
        titleTop: "Did You Know?",
        description: "Three Polish Americans left homes in Muskegon to fight in the Blue Army during the “Miracle on the Vistula.",
        summary: "Muskegon Heroes in the Blue Army",
        mainImage: require("../assets/content_images/Rebirth/Rebirth_5.png"),
        relatedIds: ["c7", "c18","c2"],
    },
    c13: {
        id: "c13",
        eraKeys: ["ww2"],
        yearLabel: "1939",
        titleTop: "Did You Know?",
        description: "In 1939 after just 21 years of independence, Poland was attacked by Nazi Germany and the Soviet Union. Poles fought with skill and courage but received no help and Poland was again partitioned by her enemies.",
        summary: "Invasion of Poland",
        mainImage: require("../assets/content_images/WW_II/WW_II_1.png"),
        relatedIds: ["c17", "c25","c27"],
    },
    c14: {
        id: "c14",
        eraKeys: ["ww2"],
        yearLabel: "1939",
        titleTop: "Did You Know?",
        description: "In 1939, Poland had Europe’s largest and most vibrant Jewish community numbering 3.3 million. The Germans targeted all Jews for extermination and sought to murder or enslave all Polish Christians.",
        summary: "Germans targeted Polish Jews, Christians.",
        mainImage: require("../assets/content_images/WW_II/WW_II_2.png"),
        relatedIds: ["c32", "c26","c15"],
    },
    c15: {
        id: "c15",
        eraKeys: ["ww2"],
        yearLabel: "1939-1941",
        titleTop: "Did You Know?",
        description: "From 1939-41 the USSR invaded eastern Poland and deported 1.7 million Poles to Siberian slave-labor camps.",
        summary: "USSR deported Poles to Siberia.",
        mainImage: require("../assets/content_images/WW_II/WW_II_3.png"),
        relatedIds: ["c32", "c26"],
    },
    c16: {
        id: "c16",
        eraKeys: ["ww2"],
        yearLabel: "1939",
        titleTop: "Did You Know?",
        description: "The Germans killed 3 million Polish Jews and 2 million Polish Christians while 500,000 to 750,000 Poles were killed by the Soviets or Ukrainian nationalists.",
        summary: "The Germans killed 3 million Polish Jews...",
        mainImage: require("../assets/content_images/WW_II/WW_II_4.png"),
        relatedIds: ["c14", "c15"],
    },
    c17: {
        id: "c17",
        eraKeys: ["ww2"],
        yearLabel: "1939",
        titleTop: "Did You Know?",
        description: "Yet again Poles refused to give up and fought alongside the Allies on every front until victory was won.",
        summary: "Polish resistance and joining the Allies",
        mainImage: require("../assets/content_images/WW_II/WW_II_5.png"),
        relatedIds: ["c13", "c25","c27"],
    },
    c18: {
        id: "c18",
        eraKeys: ["ww2"],
        yearLabel: "1939-1945",
        titleTop: "Did You Know?",
        description: "Members of one Muskegon family were shipped on cattle cars from their homes in Poland to concentration camps in Siberia in World War II. Two died and four returned home.",
        summary: "Muskegon Family’s WWII Tragedy",
        mainImage: require("../assets/content_images/WW_II/WW_II_6.png"),
        relatedIds: ["c7", "c12","c2"],
    },
    c19: {
        id: "c19",
        eraKeys: ["ww2"],
        yearLabel: "1941",
        titleTop: "Enigma in Russia",
        description: "German soldiers used the Enigma machine to encrypt critical communications during their campaigns on the Eastern Front against the Soviet Union. This photo shows Wehrmacht personnel working with a field-deployed Enigma machine in rough outdoor conditions. Despite Germany's reliance on Enigma, Allied breakthroughs in codebreaking (initiated by Polish cryptographers) severely compromised German operations.",
        summary: "Allies led by Polish scientists cracked German Enigma",
        mainImage: require("../assets/content_images/WW_II/WW_II_7.png"),
        relatedIds: ["c29", "c22"],
    },
    c20: {
        id: "c20",
        eraKeys: ["ww2"],
        yearLabel: "1944",
        titleTop: "Błyskawica Radio",
        description: '"Błyskawica" was a secret Polish radio station broadcasting during the Warsaw Uprising. It spread news, coordinated resistance, and boosted morale. Despite danger, it remained on air through much of the fighting.',
        summary: "Voice of the Uprising",
        mainImage: require("../assets/content_images/WW_II/WW_II_8.png"),
        relatedIds: ["c24", "c31","c33"],
    },
    c21: {
        id: "c21",
        eraKeys: ["ww2"],
        yearLabel: "1944",
        titleTop: "Kiliński Battalion",
        description: "Polish Home Army fighters from Battalion Kiliński stand ready during the Warsaw Uprising. Many wore captured German uniforms for camouflage. They symbolized Polish determination against Nazi occupation.",
        summary: "Polish fighters, disguised, embody defiance against Nazis",
        mainImage: require("../assets/content_images/WW_II/WW_II_9.png"),
        relatedIds: ["c30", "c23","c24"],
    },
    c22: {
        id: "c22",
        eraKeys: ["ww2"],
        yearLabel: "",
        titleTop: "Enigma Machines Exhibit",
        description: "This exhibit at the National Cryptologic Museum showcases seven different Enigma machines used by Nazi Germany during World War II. The display highlights the technological complexity of the Enigma and its role in wartime communications. It also honors the Allied efforts, especially by Polish, British, and American cryptologists, in breaking the Enigma code.",
        summary: "Seven Enigma machines on display at the National Cryptologic Museum",
        mainImage: require("../assets/content_images/WW_II/WW_II_10.png"),
        relatedIds: ["c19", "c29"],
    },
    c23: {
        id: "c23",
        eraKeys: ["ww2"],
        yearLabel: "1944",
        titleTop: "Ruins of Warsaw",
        description: "Warsaw was systematically destroyed by German forces after the Uprising failed. Over 85% of the city was reduced to rubble. This destruction was intended as punishment and warning to other occupied nations.",
        summary: "Aftermath of uprising",
        mainImage: require("../assets/content_images/WW_II/WW_II_11.png"),
        relatedIds: ["c30", "c24","c31"],
    },
    c24: {
        id: "c24",
        eraKeys: ["ww2"],
        yearLabel: "1945",
        titleTop: "Liberation",
        description: "Polish-Jewish prisoners celebrate liberation after years of Nazi captivity. Many survivors faced immense hardship even after freedom. Liberation revealed the full horror of the Holocaust to the world.",
        summary: "Liberated Polish Jews endured hardship, revealed Holocaust",
        mainImage: require("../assets/content_images/WW_II/WW_II_21.png"),
        relatedIds: ["c23", "c31","c33"],
    },
    c25: {
        id: "c25",
        eraKeys: ["ww2"],
        yearLabel: "1939",
        titleTop: "Did You Know?",
        description: "Polish codebreakers cracked Germany’s “unbreakable” Enigma cypher, allowing the Allies to read secret Nazi communications.",
        summary: "Polish codebreakers cracking Enigma",
        mainImage: require("../assets/content_images/WW_II/WW_II_12.png"),
        relatedIds: ["c17", "c27","c28"],
    },
    c26: {
        id: "c26",
        eraKeys: ["ww2"],
        yearLabel: "",
        titleTop: "Did You Know?",
        description: "Occupied Poland was the only place where the Germans decreed that any help for Jews was punishable by death for the helper and their entire family.",
        summary: "Helping Jews meant death penalty",
        mainImage: require("../assets/content_images/WW_II/WW_II_13.png"),
        relatedIds: ["c14", "c15"],
    },
    c27: {
        id: "c27",
        eraKeys: ["ww2"],
        yearLabel: "1939",
        titleTop: "Did You Know?",
        description: "One in five pilots defending London during the Battle of Britain were Polish and Polish pilots had the best ratios of kills of losses of any Allied squadrons.",
        summary: "Polish pilots in the Battle of Britain",
        mainImage: require("../assets/content_images/WW_II/WW_II_14.png"),
        relatedIds: ["c25", "c28","c13"],
    },
    c28: {
        id: "c28",
        eraKeys: ["ww2"],
        yearLabel: "1939",
        titleTop: "Did You Know?",
        description: "The Poles fought the Nazis in Norway, Africa, Italy, and France, distinguishing themselves in the Battle of Falaise and Monte Cassino among others.",
        summary: "Polish forces fighting globally",
        mainImage: require("../assets/content_images/WW_II/WW_II_15.png"),
        relatedIds: ["c7", "c12", "c18"],
    },
    c29: {
        id: "c29",
        eraKeys: ["ww2"],
        yearLabel: "1940",
        titleTop: "Battle of France Soldier Using Enigma",
        description: "During the 1940 Battle of France, German soldiers used the Enigma machine to encrypt and decrypt secret communications. The photo shows Wehrmacht officers operating the cipher machine inside a military vehicle, illustrating the importance of secure messaging in Blitzkrieg warfare. Polish and Allied codebreakers' early work on Enigma would later prove crucial to turning the tide of World War II.",
        summary: "German soldiers using Enigma for secure communication during 1940 operations",
        mainImage: require("../assets/content_images/WW_II/WW_II_16.png"),
        relatedIds: ["c19", "c22"],
    },
    c30: {
        id: "c30",
        eraKeys: ["ww2"],
        yearLabel: "1943",
        titleTop: "Warsaw Ghetto Arrest",
        description: "Nazi forces round up Jewish civilians during the Warsaw Ghetto Uprising.The iconic image of the terrified boy became a global symbol of Nazi atrocities.Most captives were sent to concentration camps afterward.",
        summary: "Jews captured by Nazis", 
        mainImage: require("../assets/content_images/WW_II/WW_II_17.png"),
        relatedIds: ["c21", "c23","c24"],
    },
    c31: {
        id: "c31",
        eraKeys: ["ww2"],
        yearLabel: "1944",
        titleTop: "Old Town Battle",
        description: "The Warsaw Old Town was the site of intense fighting during the Uprising. Polish insurgents fiercely defended historic areas against overwhelming German forces. The area suffered massive destruction but became a symbol of Polish resistance.",
        summary: "Fighting in Warsaw streets", 
        mainImage: require("../assets/content_images/WW_II/WW_II_18.png"),
        relatedIds: ["c24", "c33", "c20"],
    },
    c32: {
        id: "c32",
        eraKeys: ["ww2"],
        yearLabel: "1944",
        titleTop: "Did You Know?",
        description: "The Poles formed a secret resistance force, the largest in Europe, known as the Home Army to fight back. They tied down Germans troops, sabotaged supplies, gathered intelligence, and fought the Nazis valiantly in the Warsaw Uprising of 1944.",
        summary: "Polish resistance fought Nazi occupation",
        mainImage: require("../assets/content_images/WW_II/WW_II_19.png"),
        relatedIds: ["c14", "c26", "c15"],
    },
    c33: {
        id: "c33",
        eraKeys: ["ww2"],
        yearLabel: "",
        titleTop: "Capture Nazi Flag",
        description: "Polish resistance fighters proudly captured a Nazi vehicle and flag during the Uprising. This symbolic victory boosted morale among fighters and civilians. Every captured enemy symbol represented hope for liberation.",
        summary: "Polish Victory Moment",
        mainImage: require("../assets/content_images/WW_II/WW_II_20.png"),
        relatedIds: ["c24", "c31", "c20"],
    },
    c34: {
        id: "c34",
        eraKeys: ["communist", "modern"],
        yearLabel: "1945",
        titleTop: "Did You Know?",
        description: "Despite helping defeat Hitler, Poland was handed over to the Soviets in 1945 and a communist puppet government was installed which cruelly repressed the people.",
        summary: "Poland oppressed under Soviet control",
        mainImage: require("../assets/content_images/CommunistPoland/CommunistPoland_1.png"),
        relatedIds: ["c35", "c36","c37"],
    },
    c35: {
        id: "c35",
        eraKeys: ["communist"],
        yearLabel: "1978",
        titleTop: "Did You Know?",
        description: "The Poles continued a non-violent fight for freedom and the Catholic Church emerged as a bulwark of resistance to totalitarianism. In 1978, Karol Wojtyła was elected as Pope John Paul II, the first non-Italian pope in 450 years. The new pope encouraged non-violent resistance based on universal moral principles that united society and inspired the creation of the Solidarity free trade movement in 1980.",
        summary: "Pope inspired Polish non-violent resistance",
        mainImage: require("../assets/content_images/CommunistPoland/CommunistPoland_2.png"),
        relatedIds: ["c34", "c36","c37"],
    },
    c36: {
        id: "c36",
        eraKeys: ["modern"],
        yearLabel: "1989",
        titleTop: "Did You Know?",
        description: "Despite severe repression, Solidarity persisted and in 1989 the communist regime agreed to the first free elections, which Solidarity won in a landslide.",
        summary: "Solidarity won Poland’s free elections",
        mainImage: require("../assets/content_images/ModernPoland/ModernPoland_2.png"),
        relatedIds: ["c34", "c35","c37"],
    },
    c37: {
        id: "c37",
        eraKeys: ["modern"],
        yearLabel: "",
        titleTop: "Did You Know?",
        description: "The collapse of communism in Poland led to the fall of communist regimes across eastern & central Europe and the end of the Cold War.",
        summary: "Poland’s shift ended Cold War",
        mainImage: require("../assets/content_images/ModernPoland/ModernPoland_3.png"),
        relatedIds: ["c34", "c35","c36"],
    },
    c38: {
        id: "c38",
        eraKeys: ["modern"],
        yearLabel: "1989-Present",
        titleTop: "Did You Know?",
        description: "Today, Poland is a free nation with a growing economy based on manufacturing and high-tech industries.",
        summary: "Poland thrives today with manufacturing, technology economy",
        mainImage: require("../assets/content_images/ModernPoland/ModernPoland_4.png"),
        relatedIds: ["c34", "c35","c36"],
    },
};


export const ERA_TABS: EraTab[] = [
    { key: "all", label: "All" },
    { key: "golden_age", label: "The Golden Age" },
    { key: "wars_partitions", label: "The Era of Wars & Partitions" },
    { key: "independence", label: "Struggle for Independence" },
    { key: "rebirth", label: "Rebirth of Poland" },
    { key: "ww2", label: "World War II & Occupation" },
    { key: "communist", label: "Communist Poland" },
    { key: "modern", label: "Modern Poland" },
];

// In a real app, this data would come from an API or database
export const MOCK_CARDS: ContentCardItem[] = [
    {
        id: "c1",
        eraKeys: ["golden_age"],
        yearLabel: "1400s",
        titleTop: "Did You Know?",
        titleBottom: "Poland protected religious freedom early",
        imageUri: require("../assets/content_images/GoldenAge/GoldenAge_1.png"),
    },
    {
        id: "c2",
        eraKeys: ["golden_age"],
        yearLabel: "",
        titleTop: "Did You Know?",
        titleBottom: "When voting rights were rare, Poland had them",
        imageUri: require("../assets/content_images/GoldenAge/GoldenAge_2.png"),
    },
    {
        id: "c3",
        eraKeys: ["wars_partitions"],
        yearLabel: "1791",
        titleTop: "Did You Know?",
        titleBottom: "Poland wrote the world's second constitution",
        imageUri: require("../assets/content_images/WarsAndPartitions/WarsAndPartitions_1.png"),
    },
    {
        id: "c4",
        eraKeys: ["wars_partitions"],
        yearLabel: "1792",
        titleTop: "Did You Know?",
        titleBottom: "How corruption undermined Poland's freedom",
        imageUri: require("../assets/content_images/WarsAndPartitions/WarsAndPartitions_2.png"),
    },
    {
        id: "c5",
        eraKeys: ["wars_partitions"],
        yearLabel: "1795",
        titleTop: "Did You Know?",
        titleBottom: "How Poland vanished for 123 years",
        imageUri: require("../assets/content_images/WarsAndPartitions/WarsAndPartitions_3.png"),
    },
    {
        id: "c6",
        eraKeys: ["wars_partitions"],
        yearLabel: "",
        titleTop: "Did You Know?",
        titleBottom: "Polish heroes helped win American freedom",
        imageUri: require("../assets/content_images/WarsAndPartitions/WarsAndPartitions_4.png"),
    },
    {
        id: "c7",
        eraKeys: ["independence"],
        yearLabel: "",
        titleTop: "Did You Know?",
        titleBottom: "Polish Roots in Michigan",
        imageUri: require("../assets/content_images/Independence/Independence_1.png"),
    },
    {
        id: "c8",
        eraKeys: ["rebirth"],
        yearLabel: "1918",
        titleTop: "Did You Know?",
        titleBottom: "After WWI, Russia, Austria, and Germany collapsed and Poland regained her ...",
        imageUri: require("../assets/content_images/Rebirth/Rebirth_1.png"),
    },
    {
        id: "c9",
        eraKeys: ["rebirth"],
        yearLabel: "1920",
        titleTop: "Did You Know?",
        titleBottom: "Poles from America joined the Polish Army and provided millions of dollars in ...",
        imageUri: require("../assets/content_images/Rebirth/Rebirth_2.png"),
    },
    {
        id: "c10",
        eraKeys: ["rebirth"],
        yearLabel: "1920",
        titleTop: "Did You Know?",
        titleBottom: "After the Russian Revolution, the Communist Red Army sought to crush ...",
        imageUri: require("../assets/content_images/Rebirth/Rebirth_3.png"),
    },
    {
        id: "c11",
        eraKeys: ["rebirth"],
        yearLabel: "1920",
        titleTop: "Did You Know?",
        titleBottom: "Though outnumbered and alone, the Poles defeated the Communist invasion and ...",
        imageUri: require("../assets/content_images/Rebirth/Rebirth_4.png"),
    },
    {
        id: "c12",
        eraKeys: ["rebirth"],
        yearLabel: "1920",
        titleTop: "Did You Know?",
        titleBottom: "Muskegon Heroes in the Blue Army",
        imageUri: require("../assets/content_images/Rebirth/Rebirth_5.png"),
    },
    {
        id: "c13",
        eraKeys: ["ww2"],
        yearLabel: "1939",
        titleTop: "Did You Know?",
        titleBottom: "Invasion of Poland",
        imageUri: require("../assets/content_images/WW_II/WW_II_1.png"),
    },
    {
        id: "c14",
        eraKeys: ["ww2"],
        yearLabel: "1939",
        titleTop: "Did You Know?",
        titleBottom: "Germans targeted Polish Jews, Christians",
        imageUri: require("../assets/content_images/WW_II/WW_II_2.png"),
    },
    {
        id: "c15",
        eraKeys: ["ww2"],
        yearLabel: "1939-41",
        titleTop: "Did You Know?",
        titleBottom: "USSR deported Poles to Siberia",
        imageUri: require("../assets/content_images/WW_II/WW_II_3.png"),
    },
    {
        id: "c16",
        eraKeys: ["ww2"],
        yearLabel: "1939",
        titleTop: "Did You Know?",
        titleBottom: "The Germans killed 3 million Polish Jews...",
        imageUri: require("../assets/content_images/WW_II/WW_II_4.png"),
    },
    {
        id: "c17",
        eraKeys: ["ww2"],
        yearLabel: "1939",
        titleTop: "Did You Know?",
        titleBottom: "Polish resistance and joining the Allies",
        imageUri: require("../assets/content_images/WW_II/WW_II_5.png"),
    },
    {
        id: "c18",
        eraKeys: ["ww2"],
        yearLabel: "1939",
        titleTop: "Did You Know?",
        titleBottom: "Muskegon Family's WWII Tragedy",
        imageUri: require("../assets/content_images/WW_II/WW_II_6.png"),
    },
    {
        id: "c19",
        eraKeys: ["ww2"],
        yearLabel: "1941",
        titleTop: "Enigma in Russia",
        titleBottom: "Allies led by Polish scientists cracked German Enigma",
        imageUri: require("../assets/content_images/WW_II/WW_II_7.png"),
    },
    {
        id: "c20",
        eraKeys: ["ww2"],
        yearLabel: "1944",
        titleTop: "Błyskawica Radio",
        titleBottom: "Błyskawica Radio was a voice of the uprising...",
        imageUri: require("../assets/content_images/WW_II/WW_II_8.png"),
    },
    {
        id: "c21",
        eraKeys: ["ww2"],
        yearLabel: "1944",
        titleTop: "Kiliński Battalion",
        titleBottom: "Polish fighters, disguised, embody defiance ...",
        imageUri: require("../assets/content_images/WW_II/WW_II_9.png"),
    },
    {
        id: "c22",
        eraKeys: ["ww2"],
        yearLabel: "1939",
        titleTop: "Enigma Exhibit",
        titleBottom: "Allies led by Polish scientists cracked German Enigma",
        imageUri: require("../assets/content_images/WW_II/WW_II_10.png"),
    },
    {
        id: "c23",
        eraKeys: ["ww2"],
        yearLabel: "",
        titleTop: "Ruins of Warsaw",
        titleBottom: "Warsaw was systematically destroyed by German...",
        imageUri: require("../assets/content_images/WW_II/WW_II_11.png"),
    },
    {
        id: "c24",
        eraKeys: ["ww2"],
        yearLabel: "1945",
        titleTop: "Liberation",
        titleBottom: "Liberated Polish Jews endured hardship, revealed Holocaust",
        imageUri: require("../assets/content_images/WW_II/WW_II_21.png"),
    },
    {
        id: "c25",
        eraKeys: ["ww2"],
        yearLabel: "1939",
        titleTop: "Did You Know?",
        titleBottom: "Polish codebreakers cracking Enigma",
        imageUri: require("../assets/content_images/WW_II/WW_II_12.png"),
    },
    {
        id: "c26",
        eraKeys: ["ww2"],
        yearLabel: "",
        titleTop: "Did You Know?",
        titleBottom: "Helping Jews meant death penalty",
        imageUri: require("../assets/content_images/WW_II/WW_II_13.png"),
    },
    {
        id: "c27",
        eraKeys: ["ww2"],
        yearLabel: "1939",
        titleTop: "Did You Know?",
        titleBottom: "Polish pilots in the Battle of Britain",
        imageUri: require("../assets/content_images/WW_II/WW_II_14.png"),
    },
    {
        id: "c28",
        eraKeys: ["ww2"],
        yearLabel: "1939",
        titleTop: "Did You Know?",
        titleBottom: "Polish forces fighting globally",
        imageUri: require("../assets/content_images/WW_II/WW_II_15.png"),
    },
    {
        id: "c29",
        eraKeys: ["ww2"],
        yearLabel: "1940",
        titleTop: "Battle of France ",
        titleBottom: "Enigma encryption vital in Blitzkrieg; Allies triumphed.",
        imageUri: require("../assets/content_images/WW_II/WW_II_16.png"),
    },
    {
        id: "c30",
        eraKeys: ["ww2"],
        yearLabel: "1943",
        titleTop: "Warsaw Arrests",
        titleBottom: "Terrified boy symbolizes Nazi brutality during...",
        imageUri: require("../assets/content_images/WW_II/WW_II_17.png"),
    },
    {
        id: "c31",
        eraKeys: ["ww2"],
        yearLabel: "1944",
        titleTop: "Old Town Battle",
        titleBottom: "The Warsaw Old Town was the site of intense ...",
        imageUri: require("../assets/content_images/WW_II/WW_II_18.png"),
    },
    {
        id: "c32",
        eraKeys: ["ww2"],
        yearLabel: "",
        titleTop: "Did You Know?",
        titleBottom: "Polish resistance fought Nazi occupation",
        imageUri: require("../assets/content_images/WW_II/WW_II_19.png"),
    },
    {
        id: "c33",
        eraKeys: ["ww2"],
        yearLabel: "",
        titleTop: "Did You Know?",
        titleBottom: "Polish resistance fighters proudly captured ...",
        imageUri: require("../assets/content_images/WW_II/WW_II_20.png"),
    },
    {
        id: "c34",
        eraKeys: ["communist", "modern"],
        yearLabel: "",
        titleTop: "Did You Know?",
        titleBottom: "Poland oppressed under Soviet control",
        imageUri: require("../assets/content_images/CommunistPoland/CommunistPoland_1.png"),
    },
    {
        id: "c35",
        eraKeys: ["communist"],
        yearLabel: "1978",
        titleTop: "Did You Know?",
        titleBottom: "Pope inspired Polish non-violent resistance",
        imageUri: require("../assets/content_images/CommunistPoland/CommunistPoland_2.png"),
    },
    {
        id: "c36",
        eraKeys: ["modern"],
        yearLabel: "1989",
        titleTop: "Did You Know?",
        titleBottom: "Solidarity won Poland's free elections",
        imageUri: require("../assets/content_images/ModernPoland/ModernPoland_2.png"),
    },
    {
        id: "c37",
        eraKeys: ["modern"],
        yearLabel: "",
        titleTop: "Did You Know?",
        titleBottom: "Poland’s shift ended Cold War",
        imageUri: require("../assets/content_images/ModernPoland/ModernPoland_3.png"),
    },
    {
        id: "c38",
        eraKeys: ["modern"],
        yearLabel: "",
        titleTop: "Did You Know?",
        titleBottom: "Poland thrives today with manufacturing ...",
        imageUri: require("../assets/content_images/ModernPoland/ModernPoland_4.png"),
    },

];